CREATE TABLE bank_reviews.banks (
    bank_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR2(100) NOT NULL
);

INSERT INTO banks (bank_id, bank_name) VALUES (24, 'Commercial Bank of Ethiopia');
INSERT INTO banks (bank_id, bank_name) VALUES (25, 'Bank of Absynia Ethiopia');
INSERT INTO banks (bank_id, bank_name) VALUES (26, 'Dashen Bank of Ethiopia');
